apiVersion: apps/v1
kind: Deployment
metadata:
  name: bobpick-app
  namespace: bobpick
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: bobpick-app
  template:
    metadata:
      labels:
        app: bobpick-app
    spec:
      terminationGracePeriodSeconds: 30
      serviceAccountName: bobpick-app-sa
      containers:
        - name: bobpick-app
          image: 370201257485.dkr.ecr.ap-northeast-2.amazonaws.com/bobpick/app:bc93f03
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: bobpick-app-config
            - secretRef:
                name: bobpick-app-secret
          resources:
            requests:
              cpu: 250m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          startupProbe:
            httpGet:
              path: /healthz/
              port: 8000
            failureThreshold: 6
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /healthz/
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz/
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 10
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 5"]
