apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bobpick

resources:
- deployment.yaml
- service.yaml
- configmap.yaml
- ingress.yaml
- hpa.yaml
- migrate-job.yaml

images:
- name: bobpick-app-image
  newName: 369904859006.dkr.ecr.ap-northeast-2.amazonaws.com/bobpick/app
  newTag: 1513df3
