apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bobpick

resources:
- deployment.yaml
- service.yaml
- configmap.yaml
images:
- name: 370201257485.dkr.ecr.ap-northeast-2.amazonaws.com/bobpick/app
  newTag: 1b9d1d1
